import { Geist, Geist_Mono, Inter, VT323, Creepster } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "../context/ThemeContext";

const inter = Inter({
  subsets: ['latin'],
  weight: ['400', '700'],
  variable: '--font-inter',
})

const vt323 = VT323({ 
  subsets: ["latin"], 
  weight: ["400"], 
  variable: "--font-vt323" 
});

const creepster = Creepster({ 
  subsets: ["latin"], 
  weight: ["400"], 
  variable: "--font-creepster" 
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",

};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable} ${vt323.variable}`}>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
       <ThemeProvider>
        {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
